spring:
  redis:
    host: 127.0.0.1
    port: 6666
    password: 510151
    database: 0
zuul:
  #路由前缀
  prefix: /api
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    post-service:
      path: /post/**
      serviceId: post-service
  sensitive-headers: true
  #在请求路由转发前为请求设置Host头信息
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
