spring:
  redis:
    host: 120.55.194.0
    port: 6666
    password: 510151
    database: 0
zuul:
  #路由前缀
  prefix: /api
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    post-service:
      path: /post/**
      serviceId: post-service
    mail-service:
      path: /mail/**
      serviceId: mail-service
  sensitive-headers: true
  #在请求路由转发前为请求设置Host头信息
  add-host-header: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 12000
#ribbon的超时时间
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
