spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 510151
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tieba?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6666
    password: 510151
    database: 0
  rabbitmq:
    host: 127.0.0.1
    username: springcloud
    password: 510151
  cloud:
    stream:
      bindings:
        input_login_ip_address:
          group: Service-A
          destination: login_ip_address_channel
        input_enroll_mail_verification:
          group: Service-A
          destination: enroll_mail_verification_channel
mybatis:
  mapper-locations: classpath:com/hwj/tieba/dao/mapper/*.xml
  type-aliases-package: classpath:com.hwj.tieba.entity
logging:
  level:
    com.hwj.tieba.dao: debug
mail:
  mailHost: smtp.qq.com
  account: 3047370075@qq.com
  authorizationCode : dmpihrefydpbdgdg