spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 510151
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tieba?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6666
    password: 510151
    database: 0
  rabbitmq:
    host: 127.0.0.1
    username: springcloud
    password: 510151
  #cloud:
   # stream:
    #  bindings:
     #   output_login_ip_address:
       #   destination: login_ip_address_channel
       # output_enroll_mail_verification:
       #   destination: enroll_mail_verification_channel
 # thymeleaf:
  #  prefix: http://localhost/resources/html/
  #  suffix: .html
  #  content: text/html
  #  cache: false
  #  mode: LEGACYHTML5
  #  encoding: UTF-8
mybatis:
  mapper-locations: classpath:com/hwj/tieba/dao/Mapper/*.xml
  type-aliases-package: classpath:com.hwj.tieba.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true

#日志
logging:
  level:
    com.hwj.tieba.dao: debug


